version: 2
project_name: go-httpbin

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go generate ./...
builds:

#  {{ if eq .CurrentOS "darwin" }}netcgo{{ end }}

  - id: go-httpbin-darwin-amd64
    binary: go-httpbin
    main: ./cmd/httpbin/main.go
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
#      - CC=o64-clang
#      - CXX=o64-clang++
    flags:
      - -tags=cgo
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: go-httpbin-darwin-arm64
    binary: go-httpbin
    main: ./cmd/httpbin/main.go
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CGO_ENABLED=1
#      - CC=oa64-clang
#      - CXX=oa64-clang++
    flags:
      - -tags=cgo
    ldflags:
      - -s

archives:
  - files:
      - README.md
    format_overrides:
      - format: zip
        goos: windows
    id: go-httpbin
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{if .Arm}}_{{.Arm}}{{end}}"

checksum:
  name_template: "checksums-darwin.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
