project_name: consumer
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go generate ./...
builds:

  - id: go-httpbin
    binary: go-httpbin
    main: ./cmd/httpbin/main.go
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-lc -lrt -lpthread --static"
      - -s -w -X main.version={{ .Version }}

  - id: go-httpbin-linux-arm64
    binary: go-httpbin
    main: ./cmd/httpbin/main.go
    goarch:
      - arm64
    goos:
      - linux
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-lc -lrt -lpthread --static"
      - -s -w -X main.version={{ .Version }}

  - id: go-httpbin-darwin-amd64
    binary: go-httpbin
    main: ./cmd/httpbin/main.go
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: go-httpbin-darwin-arm64
    binary: go-httpbin
    main: ./cmd/httpbin/main.go
    goarch:
      - arm64
    goos:
      - darwin
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/oa64-clang
      - CXX=/home/runner/work/osxcross/target/bin/oa64-clang++
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: go-httpbin-windows-amd64
    binary: go-httpbin
    main: ./cmd/httpbin/main.go
    goarch:
      - amd64
    goos:
      - windows
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -trimpath
      - -buildmode=exe

archives:
  - files:
      - README.md
    format_overrides:
      - format: zip
        goos: windows
    id: consumer
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{if .Arm}}_{{.Arm}}{{end}}"

nfpms:
  - builds:
      - go-httpbin
    vendor: AndriyKalashnykov
    homepage:  https://github.com/andriykalashnykov/go-httpbin
    maintainer: "Andriy Kalashnykov <andriykalashnykov@gmail.com>"
    description: "go-httpbin"
    license: GPL-3.0
    file_name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{if .Arm}}_{{.Arm}}{{end}}"
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: ^.*?doc(\([[:word:]]+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
